# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\nvision_sst\".\n\x0cStartRequest\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"!\n\x0bStopRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"9\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nstarted_at\x18\x03 \x01(\x03\"B\n\x06Status\x12\r\n\x05state\x18\x01 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\x08\x12\x13\n\x0b\x61udio_level\x18\x03 \x01(\x02\"R\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x12\n\nsession_id\x18\x04 \x01(\t\".\n\x0eHistoryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"9\n\x0fHistoryResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.vision_sst.SessionItem\"?\n\x0bSessionItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07preview\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\"\x07\n\x05\x45mpty2\xb5\x02\n\x06\x45ngine\x12=\n\x0cStartSession\x12\x18.vision_sst.StartRequest\x1a\x13.vision_sst.Session\x12\x39\n\x0bStopSession\x12\x17.vision_sst.StopRequest\x1a\x11.vision_sst.Empty\x12\x32\n\tGetStatus\x12\x11.vision_sst.Empty\x1a\x12.vision_sst.Status\x12\x36\n\x0cStreamEvents\x12\x11.vision_sst.Empty\x1a\x11.vision_sst.Event0\x01\x12\x45\n\nGetHistory\x12\x1a.vision_sst.HistoryRequest\x1a\x1b.vision_sst.HistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=28
  _globals['_STARTREQUEST']._serialized_end=74
  _globals['_STOPREQUEST']._serialized_start=76
  _globals['_STOPREQUEST']._serialized_end=109
  _globals['_SESSION']._serialized_start=111
  _globals['_SESSION']._serialized_end=168
  _globals['_STATUS']._serialized_start=170
  _globals['_STATUS']._serialized_end=236
  _globals['_EVENT']._serialized_start=238
  _globals['_EVENT']._serialized_end=320
  _globals['_HISTORYREQUEST']._serialized_start=322
  _globals['_HISTORYREQUEST']._serialized_end=368
  _globals['_HISTORYRESPONSE']._serialized_start=370
  _globals['_HISTORYRESPONSE']._serialized_end=427
  _globals['_SESSIONITEM']._serialized_start=429
  _globals['_SESSIONITEM']._serialized_end=492
  _globals['_EMPTY']._serialized_start=494
  _globals['_EMPTY']._serialized_end=501
  _globals['_ENGINE']._serialized_start=504
  _globals['_ENGINE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
